### ISSUE TITLE
0% duty cycle does not turn off led

### ISSUE THREAD

**Issue by geologic** [maxint-rd/FastPwmPin#2]
Hi

I'm using your library with attiny85 to cycle between 4 levels of PWM on a led on D1 :

```
#include <FastPwmPin.h>
#define LED_PIN 1

void setup() {
  // put your setup code here, to run once:
}

void loop() {
FastPwmPin::enablePwmPin(LED_PIN, 4000L, 0);
delay(2000);
FastPwmPin::enablePwmPin(LED_PIN, 4000L, 25);
delay(2000);
FastPwmPin::enablePwmPin(LED_PIN, 4000L, 50);
delay(2000);
FastPwmPin::enablePwmPin(LED_PIN, 4000L, 100);
delay(2000);
}
```

The problem is when PWM=0 i still see led ON, very dimmed.

If i change frequency from 4000L to 8000L, with PWM=0 led is completely off, but PWM=25 looks brighter than PWM=50

Any clue?

**Comment by maxint-rd** [comment]
Hello, thank you for submitting this issue. The behavior you experience may be due to limitations in the ATtiny85. The ATtiny85 has some peculiar behavior with regards to PWM. In the .cpp code of the library I have included some comments which may be related.

To completely explain your experience I need to reproduce and analyse it. I may be able to do so in the coming days. For now I cannot judge whether this is something that I can improve, but I will post my findings (and improve documentation/code where possible).

**Comment by maxint-rd** [comment]
Hello again, it took some time to set up a proper test environment, but just now I've been trying to reproduce your issue. 

First comments: PWM-periods of 0% and 100% are not supported in the current library. To switch a pin fully on or off you can use digitalWrite(). The lowly lit state may occur when the pin is still in input mode, or when the PWM period is very low (like 1%). Using 99 may get you the fully lit state. I will note this as a wish for a future version.

This library is aimed at generating high frequencies, higher that analogWrite provides. 4KHz is the lowest frequency this library currently supports on the ATtiny85. (See the second table in the [readme page](https://github.com/maxint-rd/FastPwmPin/blob/master/README.md) ). I will note lower frequencies on the ATtiny85 as a wish for a future version.

So I checked the test you did and measured the PWM levels and frequency using my logical analyzer, my oscilloscope and an LED on a ATtiny85. At both 4000L and 8000L my LED was properly dimmed and the measured PWM rates corresponded with the parameters provided (I tested 99, 75, 50, 25, 10 and 5). Note however that due to how the MCU generates these signals, the resolution of the period will decrease as the frequency is increased. At some frequencies 35 may be truncated to 50 and 15 may be truncated to 25.

So unfortunately I wasn't able to completely reproduce your issue, but I hope my explanation was helpful. As soon as I find sufficient time available, I will look into further improving this library.

Cheers!

**Comment by geologic** [comment]
Hi

I used digitalWrite() for 0% and 100% duty cycle and now it is working as expected.

Thanks for your help.

**Comment by maxint-rd** [comment]
FYI: I uploaded a new version of the library, supporting lower frequencies.
